spring:
  application:
    name: highload
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/highload
    username: postgres
    password: postgres

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always