spring:
  application:
    name: highload
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/highload
#    username: postgres
#    password: postgres
    master:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/highload
      username: postgres
      password: postgres

    slave1:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/highload
      username: postgres
      password: postgres

    slave2:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5434/highload
      username: postgres
      password: postgres

#  flyway:
#    url: jdbc:postgresql://localhost:5432/highload
#    username: postgres
#    password: postgres

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always