spring:
  application:
    name: dialogHighload

tarantool:
  uri: 127.0.0.1
  port: 3301

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
userService:
  url: http://localhost:8081